#!/bin/bash
#
# Embed src/client/eka-runtime.js into src/client/client_runtime.c
# Run this after editing the JS file.
#
set -euo pipefail

JS_FILE="src/client/eka-runtime.js"
OUT_FILE="src/client/client_runtime.c"

if [ ! -f "$JS_FILE" ]; then
    echo "error: $JS_FILE not found" >&2
    exit 1
fi

JS_LEN=$(wc -c < "$JS_FILE")

python3 -c "
import sys

with open('$JS_FILE', 'rb') as f:
    data = f.read()

lines = []
lines.append('/*')
lines.append(' * AUTO-GENERATED — do not edit.')
lines.append(' * Source: src/client/eka-runtime.js')
lines.append(' * Generated by: scripts/embed_client_runtime.sh')
lines.append(' */')
lines.append('')
lines.append('#include \"client_runtime.h\"')
lines.append('')
lines.append('const unsigned char EKA_CLIENT_RUNTIME[] = {')

# Emit bytes in rows of 16
for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
    if i + 16 < len(data):
        hex_bytes += ','
    lines.append('    ' + hex_bytes)

lines.append('};')
lines.append('')
lines.append('const size_t EKA_CLIENT_RUNTIME_LEN = sizeof(EKA_CLIENT_RUNTIME);')
lines.append('')

with open('$OUT_FILE', 'w') as f:
    f.write('\n'.join(lines))

print(f'Generated $OUT_FILE ($JS_LEN bytes JS)')
"
