#include "lexer/token.h"

static const char *token_names[] = {
    [TOKEN_EOF]          = "EOF",
    [TOKEN_ERROR]        = "ERROR",
    [TOKEN_NEWLINE]      = "NEWLINE",
    [TOKEN_TEXT]         = "TEXT",
    [TOKEN_LET]          = "let",
    [TOKEN_CONST]        = "const",
    [TOKEN_FUNC]         = "func",
    [TOKEN_END]          = "end",
    [TOKEN_IF]           = "if",
    [TOKEN_ELSE]         = "else",
    [TOKEN_FOR]          = "for",
    [TOKEN_IN]           = "in",
    [TOKEN_WHILE]        = "while",
    [TOKEN_TRY]          = "try",
    [TOKEN_CATCH]        = "catch",
    [TOKEN_RETURN]       = "return",
    [TOKEN_TRUE]         = "true",
    [TOKEN_FALSE]        = "false",
    [TOKEN_NULL]         = "null",
    [TOKEN_AND]          = "and",
    [TOKEN_OR]           = "or",
    [TOKEN_NOT]          = "not",
    [TOKEN_AT_GET]       = "@get",
    [TOKEN_AT_POST]      = "@post",
    [TOKEN_AT_PUT]       = "@put",
    [TOKEN_AT_DELETE]    = "@delete",
    [TOKEN_AT_PATCH]     = "@patch",
    [TOKEN_AT_IF]        = "@if",
    [TOKEN_AT_FOR]       = "@for",
    [TOKEN_AT_DO]        = "@do",
    [TOKEN_AT_ELSE]      = "@else",
    [TOKEN_AT_END]       = "@end",
    [TOKEN_AT_CSRF]      = "@csrf",
    [TOKEN_EXPR_START]   = "{{",
    [TOKEN_EXPR_END]     = "}}",
    [TOKEN_IDENTIFIER]   = "IDENTIFIER",
    [TOKEN_STRING]       = "STRING",
    [TOKEN_NUMBER]       = "NUMBER",
    [TOKEN_PLUS]         = "+",
    [TOKEN_MINUS]        = "-",
    [TOKEN_STAR]         = "*",
    [TOKEN_SLASH]        = "/",
    [TOKEN_PERCENT]      = "%",
    [TOKEN_EQ]           = "==",
    [TOKEN_NEQ]          = "!=",
    [TOKEN_APPROX_EQ]    = "~=",
    [TOKEN_GT]           = ">",
    [TOKEN_GTE]          = ">=",
    [TOKEN_LT]           = "<",
    [TOKEN_LTE]          = "<=",
    [TOKEN_ASSIGN]       = "=",
    [TOKEN_NULL_COALESCE] = "??",
    [TOKEN_NULL_SAFE]     = "?.",
    [TOKEN_DOT]           = ".",
    [TOKEN_COMMA]         = ",",
    [TOKEN_COLON]         = ":",
    [TOKEN_SEMICOLON]     = ";",
    [TOKEN_LPAREN]        = "(",
    [TOKEN_RPAREN]        = ")",
    [TOKEN_LBRACKET]      = "[",
    [TOKEN_RBRACKET]      = "]",
    [TOKEN_LBRACE]        = "{",
    [TOKEN_RBRACE]        = "}",
};

const char *eka_token_name(eka_token_type_t type) {
    if (type < TOKEN_COUNT) return token_names[type];
    return "UNKNOWN";
}
