#ifndef CLIENT_RUNTIME_H
#define CLIENT_RUNTIME_H

#include <stddef.h>

/*
 * Embedded Eka client runtime (eka-runtime.js).
 *
 * Generated by: scripts/embed_client_runtime.sh
 * Do NOT edit manually — edit src/client/eka-runtime.js and re-run the embed script.
 */

extern const unsigned char  EKA_CLIENT_RUNTIME[];
extern const size_t EKA_CLIENT_RUNTIME_LEN;

#endif /* CLIENT_RUNTIME_H */
